### ISSUE TITLE
Cannot call events inside initialized callback Froala 3.0.5

### ISSUE THREAD

**Issue by slavik-chapelskyi** [froala/react-froala-wysiwyg#198] opened 2019-08-28 10:47 UTC
**Expected behavior.**
Within the "initialized" event callback, `this.events` refers to the editor instance events.

**Actual behavior.**
Within the "initialized" event callback, `this.events` is `undefined`.
An error is thrown: 
`Uncaught TypeError: Cannot read property 'focus' of undefined`

**Steps to reproduce the problem.**
I was trying to focus editor right after initialization.
```
 events: {
	initialized: function() {
             this.events.focus();
            }
	}
```
If you `console.log(this)`, seems like `this` refers to editor instance, but you couldn't get some editor instance props (`events, html, popups`). 

**Sandbox example.**
https://codesandbox.io/s/react-froala-initialized-bug-y4hqf

**Editor version.**
v3.0.5 (This bug didn`t exist in v3.0.3)

**OS.**
Ubuntu 18.04.3 LTS

**Browser.**
Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by slavik-chapelskyi** [comment] 2019-08-28 10:54
Similar to 
https://github.com/froala/react-froala-wysiwyg/issues/175
https://github.com/froala/wysiwyg-editor/issues/3489

**Comment by brianarpie** [comment] 2019-09-11 18:56
I am also experiencing this issue!

**Comment by pleunv** [comment] 2019-09-18 11:50
Have a look at my comment [here](https://github.com/froala/wysiwyg-editor/issues/3489#issuecomment-522974145) for a temporary workaround.

**Comment by mzorzella** [comment] 2019-09-24 10:54
When can we expect a resolution to this problem? It is currently impacting our development to the point that we're seriously considering to abandon froala in favor of something else.

**Comment by aleccool213** [comment] 2019-10-22 19:27
Hmm, it seems like the test coverage for releases in Froala is seriously lacking. Always see a regression in almost every release.

**Comment by slavik-chapelskyi** [comment] 2019-10-24 09:14
Temporary workaround

```
async initialized() {
  await new Promise(resolve => setTimeout(resolve, 1));
  this.events.focus();
}
```

**Comment by slavik-chapelskyi** [comment] 2019-10-24 09:18
Seems like #191 fix the issue.

**Comment by mjb95** [comment] 2020-02-19 13:00
Unfortunately the temporary workaround above has knock-on effects.  Now there is no control over when the initialized() method completes, which could be after the containing React component's props get updated, reverting the component state back to the orignal prop values and thus causing further issues.  It would be great if #191 could be merged and added to the next release.

**Comment by rnercessian** [comment] 2020-04-25 20:17
Having the same problem here, the only way I can make it work is using a setTimeout of 3 seconds, to wait froala Editor to be ready, but I can't put it this way the site, is risky not have it complete after 3 seconds in other's browsers.. Does anybody know if 3.1 this is solved? Or anyone could work with Promise instead of callback (because this one is giving error too).

**Comment by dejanmartinovic** [comment] 2020-04-30 17:33
@rnercessian In most cases, it would be enough to set the timeout of 1ms.
```
initialized: async function() {
      await new Promise(resolve => setTimeout(resolve), 1);
      this.html.set("html set");
 }
```

**Comment by seahorsepip** [comment] 2020-05-06 13:49
```
const fixFroalaEvents = (events: { [event: string]: (...params: any[]) => any }) => ({
	initialized: function() {
		const waitUntilInitialized =() => {
			if (!this.events) {
				setTimeout(waitUntilInitialized, 100);
				return;
			}
			const { initialized, ...otherEvents } = events;
			if (initialized) {
				initialized.call(this, this);
			}
			Object.entries(otherEvents).map(([event, fn]) => this.events.on(event, (...e) => fn(...e, this), true));
		};
		setTimeout(waitUntilInitialized, 1);
	},
});
```

I currently use the above to wait 1ms, and if it's not enough another 100ms until it's enough.
I wrap my events with it like this:

```
events: fixFroalaEvents({
  initialized: editor => {
    // Do something with editor
  },
  drop: (e, editor) => {
    // Do something with e and editor
  }
}
```

**Comment by dejanmartinovic** [comment] 2020-08-20 13:03
Try to upgrade `react-froala-wysiwyg` wrapper. This issue is resolved in version 3.2.1-1.

**Comment by seahorsepip** [comment] 2020-08-20 13:05
@dejanmartinovic Great to hear this is resolved 🙌

**Comment by mjb95** [comment] 2020-08-20 13:59
Thanks!

**Comment by ilyaskarim** [comment] 2023-07-21 14:34
Fixed in https://github.com/froala/react-froala-wysiwyg/issues/198#issuecomment-677651170

**Closed by ilyaskarim** 2023-07-21 14:34 UTC
