### ISSUE TITLE
How to get Froala instance in React?

### ISSUE THREAD

**Issue by mrfambo** [froala/react-froala-wysiwyg#184] opened 2019-08-01 13:28 UTC
I need to know how can i get the Froala Editor Instance in react so i can 

1. Get the html from editor
2. Update the HTML on editor

I need to have the instance because i don't want to introduce controlled model because it re-renders the editor again and again. And secondly i am making it live collaboration so i need a way to updated the Editor content programatically. 

```
events: {
                'initialized' : function () {
                    console.log("Hi:", this)
                    this.html.set('<p>My custom paragraph.</p>')
                    _this.EditorInitialized(this)
                }
            }
```

I am trying it this way but it says this.html.set is not a function.

**(P.S: I AM LICENSED USER)**

**Comment by fsepulveda** [comment] 2019-08-06 16:23
Same problem on 'initialized' event cannot access to this.edit.off() (early version works OK)
Any change on this event ?

"froala-editor": "^3.0.4",
"react-froala-wysiwyg": "^3.0.4",

**Comment by freenetbrasil** [comment] 2019-08-08 02:46
Same here, I'm trying to use Tribute but the "events" objects is undefined:

"froala-editor": "^3.0.4",
"react-froala-wysiwyg": "^3.0.4",

                 ` initialized: function () {
                        const editor = this;

                        tribute.attach(editor.el)
                        // Here-> Can't access editor events
                        editor.events.on('keydown', function (e) {
                            if (e.which === FroalaEditor.KEYCODE.ENTER && tribute.isActive) {
                                return false;
                            }
                        }, true);
                    },`

**Comment by brandonmp** [comment] 2019-08-09 00:52
This seems like a pretty basic feature that the docs are just straight wrong about. 

Is this project maintained at all? Commit history looks like just occasional ticks in the underlying Froala version, but this component doesn't feel very react-friendly at all.

**Comment by mrfambo** [comment] 2019-08-09 21:04
The editor itself is great no doubt. But yeah using it in React is extremely pathetic. Lots of heavy workarounds for basic tasks.

**Comment by gregoryforel** [comment] 2019-08-14 01:05
Hey guys, check [that](https://codesandbox.io/s/froala-react-xrqvj) out.
I could make it work, however, I don't understand why I'm missing so many icons in the editor. 
Do you know where are the link icon, images icon, etc?
Also, how can I get an initial value in the editor, rather than the placeholder?

**Comment by mzorzella** [comment] 2019-08-15 21:43
Same problem here, I started having this problem after upgrading to React 16.9. I'm not sure if it is related to the new version of React but even upgrading to the latest react-froala (3.0.4) does not help. Now I have no way to access the editor inside the initialized event in config.

**Comment by mzorzella** [comment] 2019-08-15 21:55
Reverting back to React 16.8.6 and react-froala 3.0.2 resolved the issue of having the editor instance undefined

**Comment by brianarpie** [comment] 2019-09-11 16:13
Here's the general pattern I've been using to make it work.

```
this.config = {
    events: {
        initialized: () => {
          const editor = this.state.initControls.getEditor();
          this.tribute.attach(editor.el);
        }
    }
}

 handleManualController = initControls => {
   this.setState({ initControls });
   initControls.initialize();
 };

<FroalaEditorComponent
   onManualControllerReady={this.handleManualController}
/>
```
react@16.8.6
react-froala-wysiwyg@3.0.5

**Comment by paulohpf** [comment] 2020-03-04 18:06
This issue still not working in version 3.1.0

**Comment by mrfambo** [comment] 2020-03-04 21:28
@paulohpf Are you expecting the support response? Come on, no one will reply from them. Pathetic support team.

**Comment by paulohpf** [comment] 2020-03-12 13:48
I've created a new React Component with Froala, so I can act with Ant Design (v3.x) getFieldDecorator... But the Froala Docs won't helped enought

**Comment by casualuser** [comment] 2020-04-06 14:00
hello everyone

the first thing what I should say - yes, we're experiencing some luck of free resources to manage all the integrations repos issues in all the repos
but all requests related to this question sent via support contact form were processed immediately with an actual workaround

so the question is that page rendered a little bit faster that DOM object became available in the initialized event
we know that this is a temporary solution and working on re-worked events system

```
  events: {
    'initialized': async function () {
       await new Promise(resolve => setTimeout(resolve, 1));
      // then do what you want

      // Do something here.
      // this is the editor instance.
      console.log(this);
    }
  }
```

**Comment by RactivussDevs** [comment] 2020-05-26 16:14
Hi! what I did, is to use the 'createRef' method of 'react' in the constructor like this:
`
import { createRef, } from 'react';
constructor(props) {
 super(props);
 this.state = {
  ref: createRef({ editor: null, });
 };
}; //end of the constructor... `

Now in the render method I got the instance of the Froala Editor like this:
`
render() {
const { ref, } = this.state;
return (
<FroalaEditor ref={ref} />
);
}; //end of the render method...
`

And now I can play around with the instance of the Froala Editor from the state of my component, for example in any method of Froala Editor.
`
beforeUpload() {
 const { ref, } = this.state;
 // Do some stuff with the instance of Froala Editor...
}; //end of the beforeUpload method...
`

**Comment by chaitanya-SharePoint** [comment] 2020-08-25 18:25
Hi, below worked for me.
private _refFroala: any;
<FroalaEditorComponent
                ref={(ref) => (this._refFroala = ref)}
                tag="textarea"
                model={htmlContent}
                onModelChange={onModelChange}
                config={config}
            />
Now, you can use this global variable across your component to get the Froala editor's instance. Something like below.
const GetContent = () => {
           alert(this._refFroala.editor.html.get());
        };

<button type="button" onClick={GetContent}>Get Content</button>

Hope, this helps.

**Comment by baraubay** [comment] 2020-12-13 02:23
> Hi, below worked for me.
> 
> ```
> private _ref: any;
> <FroalaEditorComponent
>                 ref={(ref) => (this._ref = ref)}
>                 tag="textarea"
>                 model={html}
>                 onModelChange={onChange}
>                 config={config}
>             />
> ```
> 
> Now, you can use this global variable across your component to get the Froala editor's instance. Something like below.
> 
> ```
> const GetContent = () => {
>            alert(this._ref.editor.html.get());
>         };
> 
> <button type="button" onClick={GetContent}>Get Content</button>
> ```
> 
> Hope, this helps.

Works confirmed

**Comment by ilyaskarim** [comment] 2023-07-21 14:35
Fix shared in https://github.com/froala/react-froala-wysiwyg/issues/184#issuecomment-680194877, Hence closing the issue.

**Closed by ilyaskarim** 2023-07-21 14:35 UTC
